server:
  port: 8081

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/student/**
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/course/**

eureka:
  client:
    register-with-eureka: false